name: CI

# 在master分支发生push事件时触发。
on: 
  push:
    branches:
      - main
jobs: # 工作流
  build:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps: 
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: run deploy.sh # 步骤3 
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
        run: npm install && npm run deploy # 执行的命令  
      - name: Deploy to Staging My server   #部署到服务器
        uses: easingthemes/ssh-deploy@main
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_P_KEY }} #后面指定为该仓库配置的私钥
          ARGS: "-rltgoDzvO"
          # 源目录，编译后生成的文件目录
          SOURCE: 'docs/.vuepress/dist/'
          #服务器公网地址
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          #服务器用户名-一般默认root
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          #服务器中，代码部署的位置
          TARGET: '/www/wiki/'
          #去除的文件
          EXCLUDE: "/dist/, /node_modules/" 
